### ISSUE TITLE
[Bug] Demande de connexion en étant connecté

### ISSUE THREAD

**Issue by Mitchnsun** [mparpaillon/shadra#2]
- Création du compte via Google
- Connecté en tant que recrue (0XP)
- Accès à une fiche personnage depuis la page Artwork
- Sur la fiche d'un personnage, il me propose de me loguer

<img width="1433" alt="capture d ecran 2018-10-19 a 15 20 41" src="https://user-images.githubusercontent.com/1095047/47220794-09b0f980-d3b3-11e8-883c-7dfb2c82d1ad.png">
https://shadra.hatch-rpg.com/artworks(artwork:UJjk1Fi5aooqK0CgCVgn)

Navigateur: Chrome 69 Mac OS 10.13.6

**Comment by mparpaillon** [comment]
Should be fixed in v1.0
