### ISSUE TITLE
[Bug] Bouclier sur le bouton "Got it" 

### ISSUE THREAD

**Issue by Mitchnsun** [mparpaillon/shadra#3]
- Création du compte via Google
- Connecté en tant que recrue (0XP)
- Accès à une fiche personnage depuis la page Artwork
- Sur la fiche d'un personnage, le bouclier empêche le clic sur le bouton "Got it"

<img width="1433" alt="capture d ecran 2018-10-19 a 15 20 41" src="https://user-images.githubusercontent.com/1095047/47220963-8512ab00-d3b3-11e8-801c-4af25101b8ea.png">
https://shadra.hatch-rpg.com/artworks(artwork:UJjk1Fi5aooqK0CgCVgn)

Navigateur: Chrome 69 Mac OS 10.13.6

**Comment by mparpaillon** [comment]
Should be fixed in v1.0
